version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
    env_file:
      - .env
    network_mode: host
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - db-data:/var/lib/mysql
volumes:
  db-data:

